#!/bin/bash
result=0

for subdir in \
 extra-scripts \
 simple-example \
 extra-ordering \
 no-scripts \
 extra-startup
do
 pushd .
 cd $subdir
 printf "testing examples in $subdir: "
 ./startup >actual.stdout 2>actual.stderr
 if cmp actual.stdout expected.stdout
 then printf "PASS\n"
 else printf "FAIL\n"
  result=1
  printf "actual:\n"
  cat actual.stdout
  printf "expected:\n"
  cat expected.stdout
 fi
 popd
done

exit $result
