#!/bin/bash
printf "env vars passed to this script:\n"
printf "PROJECT_DIRECTORY: %s\n" "$PROJECT_DIRECTORY"
printf "SELECTED_COMPONENTS: %s\n" "$SELECTED_COMPONENTS"
printf "COMPONENT_SCRIPT: %s\n" "$COMPONENT_SCRIPT"
printf "CURRENT_COMPONENT: %s\n" "$CURRENT_COMPONENT"
printf "\ncomponent1 started up\n"
